import time
import json
from main import app_graph, SimulationState
from langchain_core.messages import HumanMessage

def print_turn(state: SimulationState):
    if state.get("director_hint"):
        print(f"\n[DIRECTOR HINT (Invisible)] -> '{state['director_hint']}'")
    
    # Parse the JSON response
    ai_msg_str = state["messages"][-1].content
    try:
        data = json.loads(ai_msg_str)
        print(f"\n[{state['current_npc'].upper()}]: {data['dialogue']}")
        print(f"  └─> [UI Action Triggered]: Emotion='{data['emotion']}', Tool='{data['ui_trigger']}'\n")
    except Exception as e:
        print(f"\n[AI]: {ai_msg_str}\n")
    print("-" * 70)

def main():
    print("=" * 70)
    print("  SIMULATION DEMO V2.0: ADVANCED ARCHITECTURE")
    print("=" * 70)
    
    state: SimulationState = {
        "messages": [],
        "rapport_score": 50,
        "director_hint": "",
        "turn_count": 0,
        "ui_state": "chat_window",
        "current_npc": "ceo",
        "npc_notes": {},
        "summary": ""
    }
    
    # --- Turn 1: Chatting with CEO ---
    msg1 = "I will implement a strict standard competency framework for all brands."
    print(f"\n[USER -> CEO]: {msg1}")
    state["messages"].append(HumanMessage(content=msg1))
    state = app_graph.invoke(state)
    print_turn(state)
    time.sleep(1)
    
    # Check internal gossip generated by CEO
    if state.get("npc_notes"):
        print(f"*[SYSTEM BACKEND]: Gossip updated -> {state['npc_notes']}*\n")
    
    # --- Turn 2: Swapping to CHRO (Multi-Persona Cross-Reference) ---
    print("\n>>> [USER SWITCHES CHAT TAB TO: CHRO] <<<")
    state["current_npc"] = "chro"
    msg2 = "Hi CHRO. I just spoke to the CEO. Let's roll out the new HR metrics."
    print(f"\n[USER -> CHRO]: {msg2}")
    state["messages"].append(HumanMessage(content=msg2))
    state = app_graph.invoke(state)
    print_turn(state)
    time.sleep(1)
    
    # --- Turn 3: User opens a UI Tool (UI-State Awareness) ---
    print("\n>>> [USER CLICKS 'KPI CALCULATOR' ON FRONTEND UI] <<<")
    state["ui_state"] = "kpi_calculator"
    msg3 = "I don't know what to put in this tool."
    print(f"\n[USER -> CHRO]: {msg3}")
    state["messages"].append(HumanMessage(content=msg3))
    state = app_graph.invoke(state)
    
    # Also showing the Memory Summarizer working
    if state.get("summary"):
        print(f"*[SYSTEM BACKEND]: Memory Summarizer activated -> '{state['summary']}'*\n")
        
    print_turn(state)

if __name__ == "__main__":
    main()
